networks:
  k6:
  grafana:

services:
  influxdb:
    container_name: influxdb_container
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail http://localhost:8086/ping || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    container_name: grafana_container
    image: grafana/grafana:8.5.21
    networks:
      - grafana
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=${GF_AUTH_ANONYMOUS_ORG_ROLE}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_AUTH_BASIC_ENABLED==${GF_AUTH_BASIC_ENABLED}
      - GF_SERVER_SERVE_FROM_SUB_PATH==${GF_SERVER_SERVE_FROM_SUB_PATH}
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    container_name: k6_container
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./dist:/dist
      - ./configs:/configs
